### PR TITLE
Send a user agent with every API request

### PR DESCRIPTION
**Pull request by GaretJax**

### CODE REVIEW

**Comment by Chive** [comment]
👍  You could additionally check for the git revision too https://github.com/aldryn/aldryn-client/blob/master/aldryn_client/cli.py#L418-L421

**Comment by GaretJax** [comment]
@kim the UA is now in the form: `aldryn-client/2.2.1-932c1cc (Darwin/15.4.0; CPython/2.7.11)` if a git commit is found

**Comment by Chive** [comment]
Awesome 👍

**Comment by stefanfoulis** [comment]
👍

**Pull request merged**
