### PR TITLE
switched error messages from string to string-array and ...

### PR DESCRIPTION
**Pull request by kinkerl**
... added linux docker ps error hints https://github.com/aldryn/aldryn-client/issues/128

Texts are not final. 
Maybe use a different way to link to external documentation in case of breaking links.

### CODE REVIEW

**Comment by kinkerl** [comment]
@intellectronica @Chive 
Please take a look at the changes. I think its sane. Look forward to your feedback.

**Comment by Chive** [comment]
Hi @kinkerl 

First of all thanks for your contribution! 

Unfortunately, your solution doesn't cover the case when using remote docker servers through docker-machine - since the docker socket is not on your host machine. Or, if there is no file at ``/var/run/docker.sock`` it would also show the error message that it's not readable (which is true but not very helpful).

I want to make some investigations on my own later this week if there's a better way of detecting that there is actually a docker server running but not accessible.

If you come up with a solution I'd be glad to hear it!

Kim

**Comment by kinkerl** [comment]
Hm thats true. 
If we look at the documentation (https://docs.docker.com/engine/quickstart/):
> The Docker client will default to connecting to unix:///var/run/docker.sock on Linux, and tcp://127.0.0.1:2376 on Windows.

Afaik, this will only change if $DOCKER_HOST is set: https://docs.docker.com/engine/reference/commandline/cli/

So if `docker ps` does not work and $DOCKER_HOST is not set, the defaults should be used and can be tested. If not, the value of $DOCKER_HOST can be tested. 

Correct?

**Comment by Chive** [comment]
Hey @kinkerl 

After some further investigation I decided to accept your PR here and will make some changes to it later (I want to extend the docker server check to include multiple commands and test for multiple versions of ``$DOCKER_HOST``). I'll ping you in the new PR so you can have a look!

Thanks for your contribution!

Best

**Comment by kinkerl** [comment]
Looking forward to it!

**Pull request merged**
