### PR TITLE
On Linux, set folder permissions to allow access by the invoking user.

### PR DESCRIPTION
**Pull request by intellectronica**

### CODE REVIEW

**Comment by GaretJax** [comment]
This is sadly the easiest way to solve the issue. A couple of notes:

* If we go down this route, I would issue a warning to the users about the permissions implications
* It is possible to `chown -R` the folder to the same UID of the linux user
* Newly uploaded media would still be owned by root, with the default permissions (the same for automatically created folders)
* User namespaces are coming soon, this can be solved using them: http://events.linuxfoundation.org/sites/events/files/slides/User%20Namespaces%20-%20ContainerCon%202015%20-%2016-9-final_0.pdf
* We should definitely add a TODO note to the code, reminding us to replace it with user NS as soon as they are available

**Comment by Chive** [comment]
Thanks for the input @GaretJax. Guess it's the only way for now then.

Codewise, a cleaner approach imo would be:
```python
if 'linux' in sys.platform:
    docker_compose = utils.get_docker_compose_cmd(path)
    check_call(
    	docker_compose('run', '--rm', 'web', 'chmod', '-R', '777', 'data')
	)

```

**Comment by GaretJax** [comment]
LGTM @Chive

**Comment by Chive** [comment]
thanks @intellectronica. I'll put in a warning and merge it

**Pull request merged**
